export const STYLES = {
  modalOverlay:     'fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4',
  modalBox:         'bg-white rounded-2xl shadow-2xl w-full max-w-md',
  modalHeader:      'flex items-center justify-between p-6 border-b border-slate-100',
  modalTitle:       'font-bold text-slate-900 flex items-center gap-2',
  modalCloseBtn:    'text-slate-400 hover:text-slate-600 text-xl leading-none',
  modalBody:        'p-6',
  modalHint:        'text-sm text-slate-500',
  modalError:       'flex items-start gap-2 p-3 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm',
  modalWarn:        'flex items-start gap-2 p-3 bg-amber-50 border border-amber-200 rounded-xl text-amber-700 text-sm',
  modalSuccess:     'flex items-start gap-2 p-3 bg-green-50 border border-green-200 rounded-xl text-green-700 text-sm',
  modalLabel:       'text-xs font-medium text-slate-600 mb-1.5 block',
  modalInputWrap:   'relative',
  modalInputIcon:   'absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-300',
  modalInput:       'w-full pl-9 pr-4 py-2.5 border border-slate-200 rounded-xl text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500',
  modalSelect:      'w-full border border-slate-200 rounded-xl px-3 py-2.5 text-sm text-slate-800 appearance-none focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white',
  modalSelectIcon:  'absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none',
  modalRolHint:     'text-xs text-slate-400 mt-1.5',
  modalFooter:      'flex gap-3 pt-2',
  modalCancelBtn:   'flex-1 py-2.5 border border-slate-200 rounded-xl text-sm font-medium text-slate-600 hover:bg-slate-50',
  modalSubmitBtn:   'flex-1 py-2.5 bg-blue-600 hover:bg-blue-700 disabled:opacity-60 text-white rounded-xl text-sm font-semibold transition-colors flex items-center justify-center gap-2',
  modalSpinner:     'w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin',
  resultSectionLabel:'text-xs font-semibold text-slate-500 mb-2 uppercase tracking-wider',
  resultBox:        'flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-xl p-3',
  resultCode:       'flex-1 text-xl font-bold text-slate-800 tracking-[0.3em]',
  resultCopyBtn:    'p-1.5 rounded-lg hover:bg-slate-200 text-slate-500 transition-colors',
  resultLinkIcon:   'w-4 h-4 text-slate-400 shrink-0',
  resultLinkText:   'flex-1 text-xs text-slate-500 truncate',
  resultExpiry:     'text-xs text-slate-400 flex items-center gap-1.5',
  resultCloseBtn:   'w-full py-2.5 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-sm font-semibold transition-colors',
  tableWrap:        'overflow-x-auto',
  table:            'w-full text-sm',
  tableHead:        'border-b border-slate-100',
  tableTh:          'text-left py-3 px-4 text-xs font-semibold text-slate-400 uppercase tracking-wider',
  tableTbody:       'divide-y divide-slate-50',
  tableTr:          'hover:bg-slate-50 transition-colors',
  tableTd:          'py-3 px-4',
  tableCellMuted:   'py-3 px-4 text-slate-500',
  tableCellSm:      'py-3 px-4 text-slate-400 text-xs',
  tableCellRight:   'py-3 px-4 text-right',
  tableActionsWrap: 'flex items-center justify-end gap-1',
  badge:            'px-2 py-1 rounded-full text-xs font-medium',
  toggleBtn:        'p-1.5 rounded-lg text-slate-400 hover:text-blue-600 hover:bg-blue-50 transition-colors',
  toggleActiveBtn:  'p-1.5 rounded-lg transition-colors text-slate-400 hover:text-orange-600 hover:bg-orange-50',
  toggleInactiveBtn:'p-1.5 rounded-lg transition-colors text-slate-400 hover:text-green-600 hover:bg-green-50',
  deleteBtn:        'p-1.5 rounded-lg text-slate-400 hover:text-red-600 hover:bg-red-50 transition-colors',
  invDeactivateBtn: 'px-2 py-1 rounded-lg text-xs text-slate-500 hover:text-red-600 hover:bg-red-50 border border-slate-200 hover:border-red-200 transition-colors',
  invReactivateBtn: 'px-2 py-1 rounded-lg text-xs text-green-700 hover:bg-green-50 border border-green-200 transition-colors',
  invCode:          'text-xs font-mono text-slate-600 bg-slate-100 px-2 py-0.5 rounded',
  emptyState:       'text-center py-16 text-slate-400',
  emptyIcon:        'w-10 h-10 mx-auto mb-3 opacity-30',
  page:             'p-6 max-w-6xl mx-auto',
  pageHeader:       'flex items-center justify-between mb-6',
  pageTitle:        'text-2xl font-bold text-slate-900 flex items-center gap-2',
  pageSubtitle:     'text-sm text-slate-400 mt-0.5',
  inviteBtn:        'flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-semibold transition-colors shadow-sm shadow-blue-200',
  statsGrid:        'grid grid-cols-3 gap-4 mb-6',
  statCard:         'bg-white rounded-2xl border border-slate-100 p-4 flex items-center gap-4',
  statIconBox:      'w-10 h-10 rounded-xl flex items-center justify-center shrink-0',
  statValue:        'text-2xl font-bold text-slate-900',
  statLabel:        'text-xs text-slate-400 font-medium',
  tabsCard:         'bg-white rounded-2xl border border-slate-100 shadow-sm',
  tabsRow:          'flex overflow-x-auto border-b border-slate-100 scrollbar-none',
  tabBtnBase:       'flex items-center gap-2 px-5 py-4 text-sm font-semibold border-b-2 transition-colors whitespace-nowrap',
  tabBtnInactive:   'border-transparent text-slate-400 hover:text-slate-600',
  tabCountActive:   'px-1.5 py-0.5 rounded-full text-xs',
  tabCountInactive: 'px-1.5 py-0.5 rounded-full text-xs bg-slate-100 text-slate-400',
  tabContent:       'min-h-[320px]',
  tabLoading:       'py-16 text-center text-slate-400 text-sm',
  iconSm:           'w-4 h-4',
  iconSendLg:       'w-5 h-5 text-blue-600',
  iconUsersLg:      'w-6 h-6 text-blue-600',
  iconAlertSm:      'w-4 h-4 mt-0.5 shrink-0',
  iconCheckSm:      'w-4 h-4 mt-0.5 shrink-0',
  iconCopied:       'w-4 h-4 text-green-600',
  iconClockXs:      'w-3.5 h-3.5',
  selectWrap:       'relative',
  formSpace:        'space-y-4',
  emptyTextSm:      'text-sm',
  emptyTextXs:      'text-xs mt-1',
  rutText:          'text-xs text-slate-400',
  expiredBadge:     'ml-1 text-red-500',
  userNameCell:     'font-medium text-slate-700',
  userEmailCell:    'text-xs text-slate-400',
  spaceY4:          'space-y-4',
}

export const ESTADO_BADGE = {
  activo:     'bg-green-100 text-green-700',
  vacaciones: 'bg-amber-100 text-amber-700',
  inactivo:   'bg-slate-100 text-slate-500',
}

export const ROL_LABEL = {
  pabellon:     'Pabellón',
  admin_clinica:'Titular de Clínica',
  doctor:       'Médico',
}

export const ROL_BADGE = {
  pabellon:     'bg-blue-100 text-blue-700',
  admin_clinica:'bg-purple-100 text-purple-700',
  doctor:       'bg-green-100 text-green-700',
}

export const TIPO_ACTIVIDAD = {
  cirugia_aceptada:   { label: 'Cirugía aceptada',    cls: 'bg-green-100 text-green-700' },
  cirugia_rechazada:  { label: 'Cirugía rechazada',   cls: 'bg-red-100 text-red-700' },
  cirugia_reagendada: { label: 'Cirugía reagendada',  cls: 'bg-amber-100 text-amber-700' },
  cirugia_actualizada:{ label: 'Estado actualizado',  cls: 'bg-slate-100 text-slate-600' },
  bloqueo_creado:     { label: 'Bloqueo de horario',  cls: 'bg-blue-100 text-blue-700' },
  usuario_invitado:   { label: 'Usuario invitado',    cls: 'bg-purple-100 text-purple-700' },
}

export function getInvitacionStatus(inv) {
  if (inv.usado)            return { label: 'Aceptada',    cls: 'bg-green-100 text-green-700' }
  if (inv.activo === false) return { label: 'Desactivada', cls: 'bg-slate-100 text-slate-500' }
  if (new Date(inv.expires_at) < new Date()) return { label: 'Expirada', cls: 'bg-red-100 text-red-600' }
  return { label: 'Pendiente', cls: 'bg-blue-100 text-blue-700' }
}
