export const STYLES = {
  page:               'animate-in fade-in slide-in-from-right duration-500 max-w-5xl mx-auto px-4 sm:px-6 lg:px-0',
  header:             'mb-6 sm:mb-8 lg:mb-10 text-center',
  titleDark:          'text-xl sm:text-2xl lg:text-3xl font-black tracking-tighter uppercase mb-2 text-white',
  titleLight:         'text-xl sm:text-2xl lg:text-3xl font-black tracking-tighter uppercase mb-2 text-slate-900',
  subtitle:           'text-[10px] sm:text-xs font-bold uppercase tracking-widest text-slate-400',
  filtersSection:     'mb-6 sm:mb-8 space-y-3 sm:space-y-4',
  searchWrap:         'relative',
  searchIconDark:     'absolute left-3 sm:left-4 top-1/2 transform -translate-y-1/2 w-4 h-4 sm:w-5 sm:h-5 text-slate-400',
  searchIconLight:    'absolute left-3 sm:left-4 top-1/2 transform -translate-y-1/2 w-4 h-4 sm:w-5 sm:h-5 text-slate-400',
  searchInputDark:    'w-full pl-10 sm:pl-12 pr-3 sm:pr-4 py-2.5 sm:py-3 border-2 rounded-xl sm:rounded-2xl focus:border-blue-500 focus:outline-none font-bold text-sm sm:text-base transition-all touch-manipulation bg-slate-800 border-slate-700 text-white placeholder-slate-400',
  searchInputMedical: 'w-full pl-10 sm:pl-12 pr-3 sm:pr-4 py-2.5 sm:py-3 border-2 rounded-xl sm:rounded-2xl focus:border-blue-500 focus:outline-none font-bold text-sm sm:text-base transition-all touch-manipulation bg-white border-blue-200 text-slate-700 placeholder-slate-400',
  searchInputLight:   'w-full pl-10 sm:pl-12 pr-3 sm:pr-4 py-2.5 sm:py-3 border-2 rounded-xl sm:rounded-2xl focus:border-blue-500 focus:outline-none font-bold text-sm sm:text-base transition-all touch-manipulation bg-white border-slate-200 text-slate-700 placeholder-slate-400',
  filtersGrid:        'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4',
  filterLabelDark:    'text-[10px] sm:text-xs font-black uppercase tracking-widest mb-1.5 sm:mb-2 block text-slate-400',
  filterLabelLight:   'text-[10px] sm:text-xs font-black uppercase tracking-widest mb-1.5 sm:mb-2 block text-slate-400',
  filterSelectDark:   'w-full px-3 sm:px-4 py-2 sm:py-2.5 border-2 rounded-lg sm:rounded-xl focus:border-blue-500 focus:outline-none font-bold text-sm sm:text-base touch-manipulation bg-slate-800 border-slate-700 text-white',
  filterSelectMedical:'w-full px-3 sm:px-4 py-2 sm:py-2.5 border-2 rounded-lg sm:rounded-xl focus:border-blue-500 focus:outline-none font-bold text-sm sm:text-base touch-manipulation bg-white border-blue-200 text-slate-700',
  filterSelectLight:  'w-full px-3 sm:px-4 py-2 sm:py-2.5 border-2 rounded-lg sm:rounded-xl focus:border-blue-500 focus:outline-none font-bold text-sm sm:text-base touch-manipulation bg-white border-slate-200 text-slate-700',
  counterDark:        'text-xs sm:text-sm font-bold text-slate-400',
  counterLight:       'text-xs sm:text-sm font-bold text-slate-600',
  chips:              'mb-6 sm:mb-8 flex flex-wrap justify-center gap-2 sm:gap-3',
  chipActive:         'px-4 sm:px-5 py-2 sm:py-2.5 rounded-xl sm:rounded-2xl text-[10px] sm:text-xs font-black uppercase tracking-widest transition-all flex items-center gap-1.5 sm:gap-2 touch-manipulation active:scale-95 bg-blue-600 text-white shadow-lg shadow-blue-200',
  chipInactive:       'px-4 sm:px-5 py-2 sm:py-2.5 rounded-xl sm:rounded-2xl text-[10px] sm:text-xs font-black uppercase tracking-widest transition-all flex items-center gap-1.5 sm:gap-2 touch-manipulation active:scale-95 bg-white border border-slate-200 text-slate-600 hover:bg-slate-50 hover:border-blue-300',
  chipCountActive:    'px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] bg-white/20 text-white',
  chipCountInactive:  'px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] bg-slate-100 text-slate-600',
  cardsGrid:          'grid gap-4 sm:gap-6',
  cardDark:           'rounded-2xl sm:rounded-[2rem] border shadow-sm p-4 sm:p-6 lg:p-8 flex flex-col sm:flex-row items-center justify-between hover:shadow-xl transition-all bg-slate-800 border-slate-700',
  cardMedical:        'rounded-2xl sm:rounded-[2rem] border shadow-sm p-4 sm:p-6 lg:p-8 flex flex-col sm:flex-row items-center justify-between hover:shadow-xl transition-all bg-white border-blue-100',
  cardLight:          'rounded-2xl sm:rounded-[2rem] border shadow-sm p-4 sm:p-6 lg:p-8 flex flex-col sm:flex-row items-center justify-between hover:shadow-xl transition-all bg-white border-slate-100',
  cardCenter:         'flex-1 mx-0 sm:mx-4 lg:mx-6 mb-3 sm:mb-0 min-w-0 w-full sm:w-auto text-center sm:text-left',
  cardHeaderRow:      'flex flex-col sm:flex-row items-center sm:items-center gap-2 sm:gap-3 mb-2',
  cardNameDark:       'text-lg sm:text-xl font-black tracking-tight truncate w-full sm:w-auto text-white',
  cardNameLight:      'text-lg sm:text-xl font-black tracking-tight truncate w-full sm:w-auto text-slate-800',
  cardMetaDark:       'text-[10px] sm:text-xs font-bold mt-1 uppercase tracking-widest break-words sm:break-normal text-slate-400',
  cardMetaLight:      'text-[10px] sm:text-xs font-bold mt-1 uppercase tracking-widest break-words sm:break-normal text-slate-500',
  cardDoctorDark:     'text-blue-400',
  cardDoctorLight:    'text-blue-600',
  reagendBadgeDark:   'mt-2 px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 w-fit bg-amber-900/40 text-amber-200 border border-amber-700',
  reagendBadgeLight:  'mt-2 px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 w-fit bg-amber-100 text-amber-900 border border-amber-200',
  cardActions:        'mt-3 grid grid-flow-col auto-cols-max gap-2 sm:gap-3 items-center justify-start',
  viewBtnDark:        'px-3 py-2 rounded-full transition-all border touch-manipulation active:scale-95 inline-flex items-center justify-center text-blue-400 hover:bg-blue-900/30 border-blue-800 hover:border-blue-600',
  viewBtnLight:       'px-3 py-2 rounded-full transition-all border touch-manipulation active:scale-95 inline-flex items-center justify-center text-blue-600 hover:bg-blue-50 border-blue-100 hover:border-blue-300',
  acceptBtn:          'bg-green-600 hover:bg-green-700 disabled:bg-green-400 text-white px-4 py-2 rounded-full font-black text-[10px] uppercase tracking-[0.15em] shadow-md active:scale-95 transition-all inline-flex items-center justify-center gap-2',
  reagendarBtn:       'bg-amber-500 hover:bg-amber-600 text-white px-4 py-2 rounded-full font-black text-[10px] uppercase tracking-[0.15em] shadow-md active:scale-95 transition-all inline-flex items-center justify-center gap-2',
  gestionarBtn:       'bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-full font-black text-[10px] uppercase tracking-[0.15em] shadow-md active:scale-95 transition-all inline-flex items-center justify-center',
  gestionarHoraBtn:   'bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-full font-black text-[10px] uppercase tracking-[0.15em] shadow-md active:scale-95 transition-all inline-flex items-center justify-center',
  detailOverlay:      'fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4',
  detailBoxDark:      'rounded-[2rem] p-8 max-w-3xl w-full max-h-[90vh] overflow-y-auto custom-scrollbar bg-slate-800',
  detailBoxLight:     'rounded-[2rem] p-8 max-w-3xl w-full max-h-[90vh] overflow-y-auto custom-scrollbar bg-white',
  detailHeaderRow:    'flex justify-between items-center mb-6',
  detailTitleDark:    'text-2xl font-black uppercase tracking-tight text-white',
  detailTitleLight:   'text-2xl font-black uppercase tracking-tight text-slate-900',
  detailCloseDark:    'p-2 rounded-xl transition-colors hover:bg-slate-700',
  detailCloseLight:   'p-2 rounded-xl transition-colors hover:bg-slate-100',
  detailCloseIconDark:'w-5 h-5 text-slate-300',
  detailCloseIconLight:'w-5 h-5 text-slate-600',
  detailSections:     'space-y-6',
  patientSectionDark: 'rounded-2xl p-6 border bg-slate-700/50 border-slate-600',
  patientSectionMed:  'rounded-2xl p-6 border bg-blue-50 border-blue-100',
  patientSectionLight:'rounded-2xl p-6 border bg-slate-50 border-slate-100',
  sectionIconRowUser: 'flex items-center gap-3 mb-4',
  userIconDark:       'w-10 h-10 rounded-xl flex items-center justify-center bg-blue-900/50',
  userIconLight:      'w-10 h-10 rounded-xl flex items-center justify-center bg-blue-100',
  userIconInnerDark:  'w-5 h-5 text-blue-400',
  userIconInnerLight: 'w-5 h-5 text-blue-600',
  sectionTitleDark:   'text-lg font-black uppercase tracking-tight text-white',
  sectionTitleLight:  'text-lg font-black uppercase tracking-tight text-slate-900',
  detailGrid2:        'grid grid-cols-2 gap-4',
  fieldLabelDark:     'text-xs font-black uppercase tracking-wider mb-1 text-slate-400',
  fieldLabelLight:    'text-xs font-black uppercase tracking-wider mb-1 text-slate-400',
  fieldValueDark:     'text-sm font-bold text-white',
  fieldValueLight:    'text-sm font-bold text-slate-700',
  staticSection:      'bg-slate-50 rounded-2xl p-6 border border-slate-100',
  detailCloseFooter:  'mt-6 flex justify-end',
  iconCalClock:       'w-3.5 h-3.5 flex-shrink-0',
  iconSm4:            'w-4 h-4',
  iconWrapGreen:      'w-10 h-10 rounded-xl bg-green-100 flex items-center justify-center',
  iconGreen:          'w-5 h-5 text-green-600',
  iconWrapPurple:     'w-10 h-10 rounded-xl bg-purple-100 flex items-center justify-center',
  iconPurple:         'w-5 h-5 text-purple-600',
  iconWrapOrange:     'w-10 h-10 rounded-xl bg-orange-100 flex items-center justify-center',
  iconOrange:         'w-5 h-5 text-orange-600',
  iconWrapSlate:      'w-10 h-10 rounded-xl bg-slate-200 flex items-center justify-center',
  iconSlate6:         'w-5 h-5 text-slate-600',
  detailSectionTitle: 'text-lg font-black text-slate-900 uppercase tracking-tight',
  detailFieldLabel:   'text-xs font-black text-slate-400 uppercase tracking-wider mb-1',
  detailFieldValueCap:'text-sm font-bold text-slate-700 capitalize',
  mt2:                'mt-2',
  textXsSl6Bold:      'text-xs font-bold text-slate-600',
  textXsSl5Mt1:       'text-xs text-slate-500 mt-1',
  colSpan2:           'col-span-2',
  detailObsValue:     'text-sm text-slate-700 bg-white p-3 rounded-xl border border-slate-200',
  spaceY2:            'space-y-2',
  insumosItem:        'bg-white rounded-xl p-4 border border-slate-200 flex items-center justify-between',
  flex1:              'flex-1',
  flexGap3Mt1:        'flex items-center gap-3 mt-1',
  textXsSl5:          'text-xs text-slate-500',
  textXsBlue6Bold:    'text-xs text-blue-600 font-bold',
  ml4:                'ml-4',
  cantBadge:          'px-3 py-1 bg-blue-100 text-blue-700 rounded-lg text-sm font-bold',
  progOverlay:        'fixed inset-0 bg-slate-900/60 backdrop-blur-md z-[100] flex items-center justify-center p-6 animate-in fade-in duration-300',
  progBox:            'bg-white rounded-[2.5rem] w-full max-w-6xl overflow-hidden shadow-2xl border border-slate-100 flex flex-col max-h-[95vh]',
  progHeader:         'p-8 bg-slate-900 text-white flex justify-between items-center flex-shrink-0',
  progTitle:          'text-2xl font-black uppercase tracking-tighter',
  progSubtitle:       'text-blue-400 text-[10px] font-black uppercase tracking-[0.3em] mt-1',
  progCloseBtn:       'p-2 hover:bg-white/10 rounded-full transition-colors',
  iconWhite:          'text-white',
  progForm:           'p-8 space-y-8 overflow-y-auto custom-scrollbar flex-1',
  grid1gap4:          'grid grid-cols-1 gap-4',
  progLabel:          'text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1',
  progInput:          'w-full bg-slate-50 border-2 border-slate-50 rounded-2xl py-3.5 px-5 focus:border-blue-500 focus:bg-white transition-all outline-none font-bold text-slate-700',
  progCalWrap:        'flex flex-col lg:flex-row gap-6 animate-in fade-in duration-500',
  progSidebar:        'lg:w-80 flex-shrink-0 space-y-6',
  progSolCard:        'bg-slate-900 p-8 rounded-[2rem] text-white overflow-hidden relative group',
  progGlow:           'absolute top-0 right-0 w-32 h-32 bg-blue-500 rounded-full blur-[60px] opacity-20 transform translate-x-10 -translate-y-10',
  relZ10:             'relative z-10',
  progSolTitle:       'text-xs font-black uppercase tracking-[0.2em] opacity-70 mb-1',
  spaceY4Mt4:         'space-y-4 mt-4',
  progFieldLabel:     'text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1',
  progPatientName:    'text-xl font-black uppercase tracking-tighter leading-tight',
  progPatientRut:     'text-[10px] text-slate-500 font-bold uppercase mt-1',
  progOpRow:          'flex items-center gap-3 bg-white/5 p-3 rounded-2xl border border-white/10',
  iconBlue5:          'text-blue-500',
  progOpCode:         'text-[10px] font-bold uppercase tracking-widest truncate',
  progDoctorLabel:    'text-[10px] font-black text-slate-400 uppercase tracking-widest',
  progNoSol:          'text-sm font-medium opacity-50 mt-2',
  legendCard:         'bg-white rounded-[2rem] border border-slate-100 p-6',
  legendTitle:        'text-[10px] font-black text-slate-800 mb-4 flex items-center gap-2 uppercase tracking-[0.2em]',
  legendHelpIcon:     'w-4 h-4 rounded-md bg-blue-50 flex items-center justify-center text-blue-500 text-xs',
  spaceY3:            'space-y-3',
  flexGap3:           'flex items-center gap-3',
  legendDotAvail:     'w-3 h-3 rounded-full border-2 border-slate-200',
  legendLabel:        'text-xs font-bold text-slate-500 uppercase tracking-wide',
  legendDotOccup:     'w-3 h-3 rounded-full bg-red-50 border-2 border-red-100',
  legendDotBlock:     'w-3 h-3 rounded-full bg-slate-900',
  gridMain:           'flex-1 bg-white rounded-[2.5rem] border border-slate-100 p-8 shadow-sm overflow-hidden relative flex flex-col',
  gridHeaderRow:      'flex bg-slate-50 border-b border-slate-200 mb-0 flex-shrink-0',
  gridTimeCell:       'w-24 border-r border-slate-200 flex-shrink-0 flex items-center justify-center py-6',
  iconSl4:            'text-slate-400',
  gridEmptyCol:       'flex-1 text-center py-6 border-r last:border-r-0 bg-slate-50/50',
  gridColTitle4:      'text-xs font-black text-slate-400 uppercase tracking-wider leading-none',
  gridColSubSl3:      'text-[10px] font-bold text-slate-300 uppercase tracking-wider mt-1.5 block',
  gridColActive:      'flex-1 text-center py-6 border-r last:border-r-0',
  gridColTitle9:      'text-xs font-black text-slate-900 uppercase tracking-wider leading-none',
  gridColSubGreen:    'text-[10px] font-bold text-green-600 uppercase tracking-wider mt-1.5 block',
  gridRow:            'flex border-b border-slate-100 last:border-0 hover:bg-slate-50/50 transition-colors group',
  gridTimeLabel:      'w-24 border-r border-slate-200 flex-shrink-0 flex items-center justify-center py-10 text-[10px] font-bold text-slate-400 group-hover:text-blue-600 transition-colors uppercase tracking-widest',
  gridEmptyCell:      'flex-1 min-h-[110px] border-r last:border-r-0 p-2.5 bg-slate-50/30',
  gridEmptyCellInner: 'h-full w-full flex items-center justify-center border-2 border-dashed rounded-2xl border-slate-100 opacity-50',
  gridNALabel:        'text-[8px] text-slate-300 font-black uppercase tracking-widest',
  slotOccupied:       'h-full w-full bg-red-50 rounded-2xl border border-red-100 p-4 flex flex-col justify-between shadow-sm',
  slotOccTitle:       'text-[10px] font-black text-red-500 uppercase tracking-wider mb-1',
  slotOccName:        'text-xs font-bold text-red-900 leading-tight truncate',
  slotBlocked:        'h-full w-full bg-slate-900 rounded-2xl border-2 border-amber-400/50 p-4 flex flex-col justify-between shadow-lg',
  slotBlockTitle:     'text-[10px] font-black text-amber-400 uppercase tracking-wider leading-none flex items-center gap-1',
  slotBlockLabel:     'text-[11px] font-black text-white uppercase tracking-tighter leading-tight truncate',
  slotSelIcon:        'text-blue-500 animate-in zoom-in duration-300',
  selFooter:          'absolute bottom-0 left-0 right-0 bg-slate-900 text-white p-6 flex items-center justify-between animate-in slide-in-from-bottom-full duration-300 shadow-[0_-10px_40px_rgba(0,0,0,0.2)]',
  selFooterLeft:      'flex items-center gap-6',
  selFooterIcon:      'bg-blue-600 p-4 rounded-2xl',
  selFooterLabel:     'text-[9px] text-blue-400 font-black uppercase tracking-[0.3em] mb-1',
  selFooterValue:     'font-black text-xl uppercase tracking-tighter',
  selFooterSep:       'text-slate-600 mx-3',
  selFooterBtn:       'bg-blue-500 hover:bg-blue-400 text-white px-12 py-4 rounded-2xl font-black text-xs uppercase tracking-[0.2em] shadow-xl active:scale-95 transition-all',
  progTextarea:       'w-full bg-slate-50 border-2 border-slate-50 rounded-2xl py-3.5 px-5 focus:border-blue-500 focus:bg-white transition-all outline-none font-bold text-slate-700 resize-none',
  charCount:          'text-xs text-gray-500 mt-1 text-right',
  progActions:        'flex justify-end gap-4 pt-4 border-t border-slate-100',
  progCancelBtn:      'px-8 py-3.5 text-slate-400 hover:text-slate-600 font-black text-xs uppercase tracking-widest transition-colors',
  progSubmitBtn:      'bg-blue-600 hover:bg-blue-700 text-white px-12 py-3.5 rounded-2xl font-black text-xs uppercase tracking-[0.2em] shadow-xl shadow-blue-200 transition-all active:scale-95 disabled:bg-slate-200 disabled:shadow-none flex items-center justify-center gap-2',
  spaceY5:            'space-y-5',
  spaceY6:            'space-y-6',
  textSl7:            'text-slate-700',
  fontBold:           'font-bold',
  fontBlk:            'font-black',
  textSmSl5:          'text-sm text-slate-500',
  flexGap4End:        'flex gap-4 justify-end',
  btnRed:             'bg-red-600 hover:bg-red-700',
  flexStartGap3:      'flex items-start gap-3',
  iconBlue6:          'w-5 h-5 text-blue-600',
  textSmBoldSl9:      'text-sm font-bold text-slate-900',
  detailsList:        'mt-2 text-xs text-slate-700 space-y-1',
  borderRndP3:        'border rounded-xl p-3',
  grid4gap2:          'grid grid-cols-4 gap-2',
  btnBlue:            'bg-blue-600 hover:bg-blue-700',
}
