export const S = {
  page:               'space-y-3 sm:space-y-4 md:space-y-5 px-4 sm:px-5 md:px-6 lg:px-8 py-3 sm:py-4 md:py-5 lg:py-6 max-w-7xl mx-auto',
  reagendAlertDark:   'rounded-xl border px-4 py-3 flex items-center gap-3 bg-amber-900/30 border-amber-700 text-amber-100',
  reagendAlertLight:  'rounded-xl border px-4 py-3 flex items-center gap-3 bg-amber-50 border-amber-200 text-amber-900',
  header:             'flex flex-col gap-3 sm:gap-4 md:flex-row md:items-center md:justify-between mb-3 sm:mb-4 md:mb-5',
  controlsRow:        'flex flex-col gap-3 sm:flex-row sm:items-center sm:gap-4 w-full sm:w-auto',
  yearSelectorDark:   'flex items-center gap-2 border rounded-xl sm:rounded-2xl px-3 py-2 w-full sm:w-auto justify-between sm:justify-start bg-slate-800 border-slate-700',
  yearSelectorMed:    'flex items-center gap-2 border rounded-xl sm:rounded-2xl px-3 py-2 w-full sm:w-auto justify-between sm:justify-start bg-white border-blue-100',
  yearSelectorLight:  'flex items-center gap-2 border rounded-xl sm:rounded-2xl px-3 py-2 w-full sm:w-auto justify-between sm:justify-start bg-white border-slate-200',
  yearBtnDark:        'p-2 sm:p-1.5 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 touch-manipulation hover:bg-slate-700 active:bg-slate-600',
  yearBtnLight:       'p-2 sm:p-1.5 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 touch-manipulation hover:bg-slate-100 active:bg-slate-200',
  yearBtnIconDark:    'w-5 h-5 sm:w-4 sm:h-4 text-slate-300',
  yearBtnIconLight:   'w-5 h-5 sm:w-4 sm:h-4 text-slate-400',
  yearTextDark:       'text-base sm:text-sm font-bold min-w-[80px] sm:min-w-[60px] text-center text-white',
  yearTextLight:      'text-base sm:text-sm font-bold min-w-[80px] sm:min-w-[60px] text-center text-slate-700',
  searchBar:          'bg-white border border-slate-200 rounded-xl sm:rounded-2xl px-3 sm:px-4 py-2 flex items-center gap-2 sm:gap-3 w-full sm:w-auto',
  filterMsgBanner:    'bg-blue-50 border-2 border-blue-200 rounded-xl sm:rounded-2xl p-3 sm:p-4 flex items-start sm:items-center gap-2 sm:gap-3',
  legendDark:         'flex flex-wrap items-center justify-center sm:justify-end gap-2 md:gap-2.5 lg:gap-3 text-[8px] md:text-[9px] lg:text-[10px] font-black uppercase tracking-[0.3em] leading-relaxed text-slate-300',
  legendLight:        'flex flex-wrap items-center justify-center sm:justify-end gap-2 md:gap-2.5 lg:gap-3 text-[8px] md:text-[9px] lg:text-[10px] font-black uppercase tracking-[0.3em] leading-relaxed text-slate-400',
  monthCardDark:      'rounded-xl border-2 shadow-sm p-3 md:p-4 lg:p-5 flex flex-col justify-between text-left hover:border-blue-500 hover:shadow-lg hover:scale-[1.02] transition-all group min-h-[95px] md:min-h-[110px] lg:min-h-[125px] active:scale-[0.98] touch-manipulation focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 bg-slate-800 border-slate-700',
  monthCardMed:       'rounded-xl border-2 shadow-sm p-3 md:p-4 lg:p-5 flex flex-col justify-between text-left hover:border-blue-500 hover:shadow-lg hover:scale-[1.02] transition-all group min-h-[95px] md:min-h-[110px] lg:min-h-[125px] active:scale-[0.98] touch-manipulation focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 bg-white border-blue-100',
  monthCardLight:     'rounded-xl border-2 shadow-sm p-3 md:p-4 lg:p-5 flex flex-col justify-between text-left hover:border-blue-500 hover:shadow-lg hover:scale-[1.02] transition-all group min-h-[95px] md:min-h-[110px] lg:min-h-[125px] active:scale-[0.98] touch-manipulation focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 bg-white border-slate-100',
  monthNameDark:      'text-base md:text-lg lg:text-xl font-black transition-colors uppercase truncate leading-normal tracking-wide text-white group-hover:text-blue-400',
  monthNameLight:     'text-base md:text-lg lg:text-xl font-black transition-colors uppercase truncate leading-normal tracking-wide text-slate-900 group-hover:text-blue-600',
  monthSubDark:       'text-[8px] md:text-[9px] lg:text-[10px] font-bold mt-1 leading-relaxed text-slate-300',
  monthSubLight:      'text-[8px] md:text-[9px] lg:text-[10px] font-bold mt-1 leading-relaxed text-slate-500',
  monthPctDark:       'text-base md:text-lg lg:text-xl font-black leading-normal text-blue-400',
  monthPctLight:      'text-base md:text-lg lg:text-xl font-black leading-normal text-blue-600',
  monthPctLabel:      'text-[7px] md:text-[8px] lg:text-[9px] font-black uppercase tracking-[0.3em] mt-0.5 leading-relaxed text-slate-400',
  progressBgDark:     'h-2 md:h-2.5 lg:h-3 w-full rounded-full overflow-hidden shadow-inner mb-1.5 bg-slate-700',
  progressBgLight:    'h-2 md:h-2.5 lg:h-3 w-full rounded-full overflow-hidden shadow-inner mb-1.5 bg-slate-100',
  progressStatsDark:  'flex items-center justify-between text-[8px] md:text-[9px] lg:text-[10px] font-bold mt-1 leading-relaxed text-slate-300',
  progressStatsLight: 'flex items-center justify-between text-[8px] md:text-[9px] lg:text-[10px] font-bold mt-1 leading-relaxed text-slate-500',
  alertIcon:          'w-5 h-5 flex-shrink-0 text-amber-600',
  alertContent:       'flex-1',
  alertTitle:         'font-semibold text-sm',
  alertText:          'text-xs opacity-90 mt-0.5',
  alertLink:          'text-xs font-bold underline hover:no-underline',
  searchIcon:         'w-4 h-4 sm:w-5 sm:h-5 text-slate-400 flex-shrink-0',
  searchInput:        'bg-transparent text-sm sm:text-base font-bold text-slate-700 outline-none focus:ring-2 focus:ring-blue-500 rounded-xl px-2 py-1.5 sm:py-1 flex-1 min-w-0 placeholder:text-slate-400 placeholder:font-normal',
  clearBtn:           'p-1 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors',
  xIcon:              'w-4 h-4',
  filterSelect:       'bg-transparent text-sm sm:text-base font-bold text-slate-700 outline-none focus:ring-2 focus:ring-blue-500 rounded-xl px-2 py-1.5 sm:py-1 flex-1 sm:flex-none min-w-0',
  filterSearchIcon:   'w-4 h-4 sm:w-5 sm:h-5 text-blue-600 flex-shrink-0 mt-0.5 sm:mt-0',
  filterClearBtn:     'p-1.5 rounded-lg hover:bg-blue-100 text-blue-600 hover:text-blue-700 transition-colors',
  loadingText:        'text-slate-400 text-sm sm:text-base font-bold animate-pulse',
  yearLegendRow:      'flex justify-center sm:justify-end mb-3 md:mb-4',
  yearMonthGrid:      'grid grid-cols-3 gap-3 md:gap-4 lg:gap-5 animate-in fade-in slide-in-from-bottom-4 duration-500',
  legendDotItem:      'flex items-center gap-1.5 md:gap-2',
  legendDotBlue:      'w-2.5 h-2.5 md:w-3 md:h-3 rounded-full bg-blue-500 flex-shrink-0',
  legendDotYellow:    'w-2.5 h-2.5 md:w-3 md:h-3 rounded-full bg-yellow-400 flex-shrink-0',
  legendDotGray:      'w-2.5 h-2.5 md:w-3 md:h-3 rounded-full bg-slate-300 flex-shrink-0',
  whitespacenowrap:   'whitespace-nowrap',
  confirmModalBody:   'space-y-4 sm:space-y-5 md:space-y-6',
  confirmGradBox:     'bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl sm:rounded-2xl p-4 sm:p-5 md:p-6 border-2 border-blue-200',
  confirmAvatarRow:   'flex items-center gap-3 sm:gap-4 mb-3 sm:mb-4',
  confirmAvatar:      'w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 rounded-xl sm:rounded-2xl flex items-center justify-center text-white font-black text-lg sm:text-xl md:text-2xl shadow-lg bg-blue-600 flex-shrink-0',
  confirmPatientLabel:'text-[8px] sm:text-[9px] font-black text-blue-400 uppercase tracking-widest mb-0.5 sm:mb-1',
  confirmPatientName: 'font-black text-slate-900 text-base sm:text-lg md:text-xl uppercase leading-relaxed tracking-wide truncate',
  confirmPatientRut:  'text-[10px] sm:text-xs text-slate-600 font-bold mt-0.5 sm:mt-1',
  confirmProcBox:     'bg-white/60 rounded-lg sm:rounded-xl p-2.5 sm:p-3 border border-blue-200',
  confirmProcLabelRow:'text-[8px] sm:text-[9px] font-black text-blue-400 uppercase tracking-widest mb-1 flex items-center gap-1.5 sm:gap-2',
  confirmProcName:    'text-xs sm:text-sm font-black text-slate-800 break-words',
  confirmProcCode:    'text-[10px] sm:text-xs text-slate-500 font-bold mt-0.5 sm:mt-1',
  confirmGrid:        'grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4',
  confirmGridCell:    'bg-slate-50 rounded-lg sm:rounded-xl p-3 sm:p-4 border border-slate-200',
  confirmCellLabelRow:'text-[8px] sm:text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 sm:mb-2 flex items-center gap-1.5 sm:gap-2',
  confirmCellValue:   'text-sm sm:text-base font-black text-slate-900 break-words',
  horaFinLabel:       'text-[9px] sm:text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1 block',
  horaFinInput:       'w-full bg-slate-50 border-2 border-slate-200 rounded-xl sm:rounded-2xl py-3 sm:py-3.5 px-4 sm:px-5 focus:border-blue-500 focus:bg-white transition-all outline-none font-bold text-slate-700 text-base touch-manipulation',
  overlapAlert:       'mt-2 p-3 bg-red-50 border border-red-200 rounded-lg animate-pulse',
  overlapTitle:       'text-xs sm:text-sm text-red-700 font-black flex items-center gap-2',
  overlapText:        'text-[10px] sm:text-xs text-red-600 mt-1',
  confirmActions:     'flex flex-col sm:flex-row gap-3 sm:gap-4 pt-3 sm:pt-4 border-t border-slate-200',
  patientInfoBox:     'flex items-center gap-3 sm:gap-4 md:gap-5 p-3 sm:p-4 md:p-5 bg-slate-50 rounded-xl sm:rounded-2xl border border-slate-100',
  patientAvatar:      'w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 rounded-xl sm:rounded-2xl flex items-center justify-center text-white font-black text-lg sm:text-xl md:text-2xl shadow-lg bg-red-600 flex-shrink-0',
  infoBoxLabel:       'text-[8px] sm:text-[9px] font-black text-slate-400 uppercase tracking-widest mb-0.5',
  infoBoxName:        'font-black text-slate-800 text-sm sm:text-base md:text-lg uppercase leading-none break-words',
  doctorBox:          'flex items-center gap-3 sm:gap-4 md:gap-5 p-3 sm:p-4 md:p-5 bg-blue-50 rounded-xl sm:rounded-2xl border border-blue-100',
  doctorAvatar:       'w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 rounded-xl sm:rounded-2xl flex items-center justify-center text-white font-black text-lg sm:text-xl shadow-lg bg-blue-600 flex-shrink-0',
  doctorLabelBlue:    'text-[8px] sm:text-[9px] font-black text-blue-400 uppercase tracking-widest mb-0.5',
  procedureBox:       'p-3 sm:p-4 md:p-5 bg-slate-50 rounded-xl sm:rounded-2xl border border-slate-100',
  detailBox:          'p-3 sm:p-4 md:p-5 bg-white rounded-xl sm:rounded-2xl border border-slate-100',
  detailBoxBlue:      'p-3 sm:p-4 md:p-5 bg-blue-50 rounded-xl sm:rounded-2xl border border-blue-100',
  detailBoxLabelRow:  'text-[8px] sm:text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 sm:mb-2 flex items-center gap-1',
  detailBoxValue:     'font-black text-slate-800 text-sm sm:text-base',
  cancelBtnWrap:      'p-3 sm:p-4 md:p-5 bg-white rounded-xl sm:rounded-2xl border border-slate-100',
  historicoInfoBox:   'p-3 sm:p-4 md:p-5 bg-blue-50 rounded-xl sm:rounded-2xl border border-blue-100',
  historicoRow:       'flex items-center gap-2 text-blue-700',
  availableBox:       'flex items-center gap-3 sm:gap-4 md:gap-5 p-3 sm:p-4 md:p-5 bg-green-50 rounded-xl sm:rounded-2xl border border-green-100',
  availableAvatar:    'w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 rounded-xl sm:rounded-2xl flex items-center justify-center text-white font-black text-lg sm:text-xl shadow-lg bg-green-600 flex-shrink-0',
  availLabelGreen:    'text-[8px] sm:text-[9px] font-black text-green-400 uppercase tracking-widest mb-0.5',
  availableInfoBox:   'p-3 sm:p-4 md:p-5 bg-blue-50 rounded-xl sm:rounded-2xl border border-blue-100',
  availableInfoLabelRow:'text-[8px] sm:text-[9px] font-black text-blue-400 uppercase tracking-widest mb-1.5 sm:mb-2 flex items-center gap-1',
  availableInfoText:  'text-xs sm:text-sm text-slate-700 break-words',
  cancelWarningBox:   'flex items-start gap-3 sm:gap-4 p-3 sm:p-4 bg-red-50 rounded-lg sm:rounded-xl border border-red-200',
  alertTriangleIcon:  'w-5 h-5 sm:w-6 sm:h-6 text-red-600 flex-shrink-0 mt-0.5',
  cancelWarningText:  'text-xs sm:text-sm text-slate-700 space-y-1',
  cancelActionRow:    'flex flex-col sm:flex-row gap-3 sm:gap-4 justify-end',
  cancelNote:         'text-xs sm:text-sm text-slate-600',
  filterLabelSpan:    'text-[9px] sm:text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] whitespace-nowrap leading-relaxed',
  filterBannerTitle:  'text-xs sm:text-sm font-black text-blue-900 uppercase tracking-wide leading-relaxed',
  filterBannerText:   'text-[10px] sm:text-xs text-blue-700 mt-0.5 sm:mt-1',
  monthCardTop:       'flex items-start justify-between mb-2 md:mb-2.5 w-full gap-1.5 md:gap-2',
  monthCardPctWrap:   'text-right ml-1.5 md:ml-2 flex-shrink-0',
  monthCardBottom:    'mt-auto w-full',
  monthBarFlex:       'h-full flex',
  spaceY2:            'space-y-2',
  errorMsg:           'mt-2 text-xs sm:text-sm text-red-600 font-bold',
  successMsg:         'mt-2 text-xs sm:text-sm text-green-600 font-bold flex items-center gap-1',
  detailsProcLabel:   'text-[8px] sm:text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 sm:mb-2',
  detailsProcValue:   'font-black text-slate-800 text-sm sm:text-base break-words',
  stethIcon:          'sm:w-5 sm:h-5 md:w-6 md:h-6',
  checkSmall:         'sm:w-3 sm:h-3',
  checkBigGreen:      'sm:w-8 sm:h-8',
  cancelModalTitle:   'text-sm sm:text-base text-slate-900 font-bold mb-2',
  fontBold:           'font-bold',
  historicoInfo:      'text-xs sm:text-sm font-bold',
  infoMdIcon:         'sm:w-5 sm:h-5',
  xcircleCancelIcon:  'sm:w-[18px] sm:h-[18px]',
  flexOne:            'flex-1',
  monthBarBlue:       'bg-blue-500 transition-all',
  monthBarYellow:     'bg-yellow-400 transition-all',
  monthBarGray:       'bg-slate-300 transition-all',
  monthBloqSpan:      'truncate',
  monthBarOcio:       'ml-1.5 truncate',
  confirmSmIcon:      'sm:w-3 sm:h-3',
}
