-- =====================================================
-- CREAR USUARIO PABELLÓN INICIAL
-- =====================================================
-- 
-- INSTRUCCIONES:
-- 1. Primero crea el usuario en Supabase Auth:
--    - Ve a Authentication > Users
--    - Haz clic en "Add user" > "Create new user"
--    - Email: pabellon@clinica.cl (o el que prefieras)
--    - Password: (crea una contraseña segura)
--    - Auto Confirm User: ✅ Activa esta opción
--    - Haz clic en "Create user"
--    - COPIA EL USER UID que aparece
--
-- 2. Luego ejecuta este SQL reemplazando 'TU_USER_UID_AQUI' con el UID copiado:

-- INSERT INTO public.users (id, email, role)
-- VALUES (
--   'TU_USER_UID_AQUI',  -- Reemplaza con el User UID de Supabase Auth
--   'pabellon@clinica.cl',  -- El mismo email que usaste al crear el usuario
--   'pabellon'
-- );

-- Ejemplo:
-- INSERT INTO public.users (id, email, role)
-- VALUES (
--   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
--   'pabellon@clinica.cl',
--   'pabellon'
-- );
